[package]
name = "kernel"
version = "0.1.0"
authors = ["Senseiod <moyan@iouyi.top>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uart_16550 = "0.2.7"
bootloader = { path = "../bootloader" }